name: CI
on:
  pull_request:
    branches:
      - "dev"
  push:
    branches:
      - "dev"

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: [3.6]

    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install packages and pytest
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest -v